Upgrade to 0.2.2
Neutrinet/neutrinet_ynh pull request #3
Opened 2017-11-12 16:55 UTC by tbalthazar

What this upgrade does:
- renew the certificate
- add a daily cron job that will check if the certificate must be
  renewed

The `renew_from_cube` script only renew the cert if it will [expire in less than 4
months](https://github.com/Neutrinet/renew_cert/blob/master/renew_from_cube.py#L29).

2017-11-12 19:06 UTC, Psycojoker commented on scripts/upgrade
> -    get_out_of_testing
Une raison pour avoir retiré ça ?

2017-11-12 19:10 UTC, Psycojoker requested changes

2017-11-12 19:10 UTC, Psycojoker commented on scripts/upgrade
> +    git pull origin master
Ici ça ne va pas marcher car lors de l'installation on fait un checkout sur le commit exact que l'on veut utiliser https://github.com/Neutrinet/neutrinet_ynh/blob/master/scripts/install#L55 il faut donc checkout à nouveau (et probablement faire un "git fetch" ou "git remote update" à la place)

2017-11-12 19:10 UTC, Psycojoker commented on scripts/upgrade
> +cd $RENEW_CERT_PATH && git pull origin master && ve/bin/python renew_from_cube.py --cron
Pareil, le "git pull origin master" va pas faire effet ici et ça me semble bourrin en fait comme méthode et un coup à casser toutes les briques en une fois si ça merde ^^'

2017-11-12 19:41 UTC, tbalthazar commented on scripts/upgrade
> -    get_out_of_testing
Il me semble que tu m'avais dit que ça n'était pas nécessaire, et à priori le testing est retiré à l'étape précédente, non? :)

2017-11-12 19:42 UTC, tbalthazar commented on scripts/upgrade
> +    git pull origin master
Ah ok, je vais regarder, ça a marché dans mes tests sur ma brique, mais je vais double-checker.

2017-11-12 19:42 UTC, tbalthazar commented on scripts/upgrade
> +cd $RENEW_CERT_PATH && git pull origin master && ve/bin/python renew_from_cube.py --cron
comment ça casser les briques?
à priori, l'install se passe comme d'habitude sur le commit spécifié, puis lors de l'install de `neutrinet_ynh`, y'aura un `git pull` (ou autre, voir commentaire plus haut) qui récupérera la dernière version pour le cron.
dans quel cas de figure risquerait-on de casser les briques?

2017-11-12 19:42 UTC, tbalthazar commented
@Psycojoker merci pour la seconde paire d'yeux <3
Commentaires laissés également.

2017-11-12 20:23 UTC, tbalthazar commented on scripts/upgrade
> +    git pull origin master
Ok, oui, je pensais que le flag `--cron` n'était pas dispo sur ma brique parce que le repo n'était pas à jour, mais c'était en effect à cause du 'checkout`.
Du coup je reswitche sur master puis fais un pull pour être à jour.

2017-11-12 20:24 UTC, tbalthazar commented
Et je viens de commiter un truc plus clean pour revenir sur `master` de `renew_cert`, tu me diras si qqchose m'échappe. Merci!

2017-12-10 15:47 UTC, tbalthazar commented
@Psycojoker voilà, j'ai enfin fait la modif. Si tu as l'occasion de jeter un oeil ...
Pour tester:
```bash
# on your local machine
$ cd /tmp
$ git clone https://github.com/Neutrinet/neutrinet_ynh && cd neutrinet_ynh
$ scp scripts/upgrade scripts/commons root@your-cube:/tmp
$ ssh root@your-cube
$ cd /tmp
$ ./upgrade
# test cron
$ run-parts -v /etc/cron.daily
# rollback to previous version (v0.2.1)
$ yunohost app setting neutrinet version -v "0.2.1"
$ rm /etc/cron.daily/neutrinet-renew-cert
```

2017-12-11 00:23 UTC, Psycojoker commented
Je suis pas en position de tester là tout de suite mais en lecture rapide ça m'a l'air bien :)

2017-12-11 18:16 UTC, tbalthazar commented
Ok, merci. Bon, on va l'essayer en la publiant silencieusement et en demandant à quelques personnes de tester.

2017-12-11 18:16 UTC, merged